apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lwworld
  name: lwworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lwworld
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lwworld
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
